services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
